#+TITLE: M-x tramp-menu

This package shows completion with all known SSH hosts and connects to the
selected one through TRAMP. The advantage over the built-in Emacs functionality
is that you don't have to ~C-x C-f~ which Evil users are not used to, and you
don't have to remember the remote file syntax: ~/ssh:user@host:/path/to/file~.

** Installation

The package is not available in MELPA yet.

#+BEGIN_SRC emacs-lisp
(use-package tramp-menu
  :quelpa (tramp-menu
           :fetcher github
           :repo "FrostyX/tramp-menu"))
#+END_SRC

** Configuration

The ~M-x tramp-menu~ commands works out of the box without any additional
configuration required. However some options are customizable.

What shell should be opened on the remote machine?

#+BEGIN_SRC emacs-lisp
(setq tramp-menu-shell #'vterm)
#+END_SRC

The default option is ~#'shell~ but other interesting choices are ~#'eshell~,
~#'vterm~, ~#'eat~ or ~#'dired-jump~.

If you want to configure a user, proxy settings or any other SSH option,
configure your ~$HOME/.ssh/config~. For example:

#+BEGIN_SRC conf
Host abathur
    User frostyx
#+END_SRC

** Alternatives

- [[https://github.com/masasam/emacs-helm-tramp][emacs-helm-tramp]]
- [[https://github.com/charmitro/emacs-ssh-machines][emacs-ssh-machines]]
- [[https://github.com/rlupton20/mushu][mushu]]
